id: A01B50160
title: 'The Cascading Essence of Great Bliss: An Empowerment Ritual for the Female
  Practice of the Queen of Great Bliss, from the Heart-Essence of the Vast Expanse'
type: translation
pechas:
- I6A2F4F26
- I3AE37C9C
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:00:48.597427
  last_modified_at: 2023-01-04 12:00:48.597442
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  I6A2F4F26/F2C8: '5007'
  I3AE37C9C/4161: '5007'
